export const T = {
  bg: 'var(--bg)',
  card: 'var(--card)',
  ink: 'var(--ink)',
  inkSoft: 'var(--inkSoft)',
  inkMuted: 'var(--inkMuted)',
  inkFaint: 'var(--inkFaint)',
  cream: 'var(--cream)',
  creamDark: 'var(--creamDark)',
  accent: 'var(--accent)',
  accentLight: 'var(--accentLight)',
  accentGlow: 'var(--accentGlow)',
  sage: 'var(--sage)',
  sageLight: 'var(--sageLight)',
  sageDark: 'var(--sageDark)',
  amber: 'var(--amber)',
  amberLight: 'var(--amberLight)',
  danger: 'var(--danger)',
  dangerLight: 'var(--dangerLight)',
  overlay: 'var(--overlay)',
  shadow: 'var(--shadow)',
  shadowHover: 'var(--shadowHover)',
  radius: 14,
  serif: "'Playfair Display', Georgia, serif",
  sans: "'Source Sans 3', 'Segoe UI', sans-serif",
}